spring:
  datasource:
    url: jdbc:mysql:///documents?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sc.entity
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: boot_file_service
  registry:
    address: zookeeper://127.0.0.1:2181
